// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Event struct {
	RunID     string
	Seq       int64
	Type      string
	Timestamp string
	Payload   string
}

type Message struct {
	ID        string
	ThreadID  string
	Role      string
	Content   string
	CreatedAt pgtype.Timestamptz
}

type Project struct {
	ID        string
	Name      string
	CreatedAt pgtype.Timestamptz
}

type Run struct {
	ID                   string
	ProjectID            string
	ThreadID             string
	Goal                 string
	Status               string
	PlanSnapshot         string
	VerificationSnapshot string
	ArtifactPaths        string
	CreatedAt            pgtype.Timestamptz
}

type Thread struct {
	ID        string
	ProjectID string
	Title     string
	CreatedAt pgtype.Timestamptz
}
