// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addMessage = `-- name: AddMessage :exec
INSERT INTO messages (id, thread_id, role, content, created_at) VALUES ($1, $2, $3, $4, $5)
`

type AddMessageParams struct {
	ID        string
	ThreadID  string
	Role      string
	Content   string
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) AddMessage(ctx context.Context, arg AddMessageParams) error {
	_, err := q.db.Exec(ctx, addMessage,
		arg.ID,
		arg.ThreadID,
		arg.Role,
		arg.Content,
		arg.CreatedAt,
	)
	return err
}

const completeRun = `-- name: CompleteRun :exec
UPDATE runs SET status = 'completed', artifact_paths = $2 WHERE id = $1
`

type CompleteRunParams struct {
	ID            string
	ArtifactPaths string
}

func (q *Queries) CompleteRun(ctx context.Context, arg CompleteRunParams) error {
	_, err := q.db.Exec(ctx, completeRun, arg.ID, arg.ArtifactPaths)
	return err
}

const createProject = `-- name: CreateProject :exec
INSERT INTO projects (id, name, created_at) VALUES ($1, $2, $3)
`

type CreateProjectParams struct {
	ID        string
	Name      string
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) error {
	_, err := q.db.Exec(ctx, createProject, arg.ID, arg.Name, arg.CreatedAt)
	return err
}

const createRun = `-- name: CreateRun :exec
INSERT INTO runs (id, project_id, thread_id, goal, status, created_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateRunParams struct {
	ID        string
	ProjectID string
	ThreadID  string
	Goal      string
	Status    string
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) CreateRun(ctx context.Context, arg CreateRunParams) error {
	_, err := q.db.Exec(ctx, createRun,
		arg.ID,
		arg.ProjectID,
		arg.ThreadID,
		arg.Goal,
		arg.Status,
		arg.CreatedAt,
	)
	return err
}

const createThread = `-- name: CreateThread :exec
INSERT INTO threads (id, project_id, title, created_at) VALUES ($1, $2, $3, $4)
`

type CreateThreadParams struct {
	ID        string
	ProjectID string
	Title     string
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) CreateThread(ctx context.Context, arg CreateThreadParams) error {
	_, err := q.db.Exec(ctx, createThread,
		arg.ID,
		arg.ProjectID,
		arg.Title,
		arg.CreatedAt,
	)
	return err
}

const getRun = `-- name: GetRun :one
SELECT id, project_id, thread_id, goal, status, plan_snapshot, verification_snapshot, artifact_paths
FROM runs WHERE id = $1
`

type GetRunRow struct {
	ID                   string
	ProjectID            string
	ThreadID             string
	Goal                 string
	Status               string
	PlanSnapshot         string
	VerificationSnapshot string
	ArtifactPaths        string
}

func (q *Queries) GetRun(ctx context.Context, id string) (GetRunRow, error) {
	row := q.db.QueryRow(ctx, getRun, id)
	var i GetRunRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ThreadID,
		&i.Goal,
		&i.Status,
		&i.PlanSnapshot,
		&i.VerificationSnapshot,
		&i.ArtifactPaths,
	)
	return i, err
}

const getThread = `-- name: GetThread :one
SELECT id, project_id, title FROM threads WHERE id = $1
`

type GetThreadRow struct {
	ID        string
	ProjectID string
	Title     string
}

func (q *Queries) GetThread(ctx context.Context, id string) (GetThreadRow, error) {
	row := q.db.QueryRow(ctx, getThread, id)
	var i GetThreadRow
	err := row.Scan(&i.ID, &i.ProjectID, &i.Title)
	return i, err
}

const insertEvent = `-- name: InsertEvent :execrows
INSERT INTO events (run_id, seq, type, timestamp, payload)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (run_id, seq) DO NOTHING
`

type InsertEventParams struct {
	RunID     string
	Seq       int64
	Type      string
	Timestamp string
	Payload   string
}

func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertEvent,
		arg.RunID,
		arg.Seq,
		arg.Type,
		arg.Timestamp,
		arg.Payload,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listEventsAfter = `-- name: ListEventsAfter :many
SELECT run_id, seq, type, timestamp, payload
FROM events
WHERE run_id = $1 AND seq > $2
ORDER BY seq
`

type ListEventsAfterParams struct {
	RunID string
	Seq   int64
}

func (q *Queries) ListEventsAfter(ctx context.Context, arg ListEventsAfterParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, listEventsAfter, arg.RunID, arg.Seq)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.RunID,
			&i.Seq,
			&i.Type,
			&i.Timestamp,
			&i.Payload,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessages = `-- name: ListMessages :many
SELECT role, content FROM messages WHERE thread_id = $1 ORDER BY created_at
`

type ListMessagesRow struct {
	Role    string
	Content string
}

func (q *Queries) ListMessages(ctx context.Context, threadID string) ([]ListMessagesRow, error) {
	rows, err := q.db.Query(ctx, listMessages, threadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMessagesRow
	for rows.Next() {
		var i ListMessagesRow
		if err := rows.Scan(&i.Role, &i.Content); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjects = `-- name: ListProjects :many
SELECT id, name FROM projects ORDER BY created_at
`

type ListProjectsRow struct {
	ID   string
	Name string
}

func (q *Queries) ListProjects(ctx context.Context) ([]ListProjectsRow, error) {
	rows, err := q.db.Query(ctx, listProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProjectsRow
	for rows.Next() {
		var i ListProjectsRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listThreads = `-- name: ListThreads :many
SELECT id, title FROM threads WHERE project_id = $1 ORDER BY created_at
`

type ListThreadsRow struct {
	ID    string
	Title string
}

func (q *Queries) ListThreads(ctx context.Context, projectID string) ([]ListThreadsRow, error) {
	rows, err := q.db.Query(ctx, listThreads, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListThreadsRow
	for rows.Next() {
		var i ListThreadsRow
		if err := rows.Scan(&i.ID, &i.Title); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const requestCancel = `-- name: RequestCancel :execrows
UPDATE runs SET status = 'cancel_requested' WHERE id = $1 AND status = 'running'
`

func (q *Queries) RequestCancel(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, requestCancel, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setRunStatus = `-- name: SetRunStatus :exec
UPDATE runs SET status = $2 WHERE id = $1
`

type SetRunStatusParams struct {
	ID     string
	Status string
}

func (q *Queries) SetRunStatus(ctx context.Context, arg SetRunStatusParams) error {
	_, err := q.db.Exec(ctx, setRunStatus, arg.ID, arg.Status)
	return err
}

const updatePlanSnapshot = `-- name: UpdatePlanSnapshot :exec
UPDATE runs SET plan_snapshot = $2 WHERE id = $1
`

type UpdatePlanSnapshotParams struct {
	ID           string
	PlanSnapshot string
}

func (q *Queries) UpdatePlanSnapshot(ctx context.Context, arg UpdatePlanSnapshotParams) error {
	_, err := q.db.Exec(ctx, updatePlanSnapshot, arg.ID, arg.PlanSnapshot)
	return err
}

const updateVerificationSnapshot = `-- name: UpdateVerificationSnapshot :exec
UPDATE runs SET verification_snapshot = $2 WHERE id = $1
`

type UpdateVerificationSnapshotParams struct {
	ID                   string
	VerificationSnapshot string
}

func (q *Queries) UpdateVerificationSnapshot(ctx context.Context, arg UpdateVerificationSnapshotParams) error {
	_, err := q.db.Exec(ctx, updateVerificationSnapshot, arg.ID, arg.VerificationSnapshot)
	return err
}
