#!/bin/sh
set -eu
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<SQL
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE EXTENSION IF NOT EXISTS vector;
CREATE SCHEMA IF NOT EXISTS lg;
SQL
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<SQL
DO \$\$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'cd_migrate') THEN
    CREATE ROLE cd_migrate LOGIN PASSWORD '${CD_MIGRATE_PASSWORD}';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'cd_api') THEN
    CREATE ROLE cd_api LOGIN PASSWORD '${CD_API_PASSWORD}' NOSUPERUSER NOBYPASSRLS;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'cd_system') THEN
    CREATE ROLE cd_system LOGIN PASSWORD '${CD_SYSTEM_PASSWORD}' BYPASSRLS;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'cd_kernel') THEN
    CREATE ROLE cd_kernel LOGIN PASSWORD '${CD_KERNEL_PASSWORD}' NOSUPERUSER NOBYPASSRLS;
  END IF;
END
\$\$;
SQL
