// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: app.sql

package store

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAgent = `-- name: CreateAgent :one
INSERT INTO agents (name)
VALUES ($1)
RETURNING id, name, current_version, created_at, updated_at
`

func (q *Queries) CreateAgent(ctx context.Context, name string) (Agent, error) {
	row := q.db.QueryRow(ctx, createAgent, name)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CurrentVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAgent = `-- name: GetAgent :one
SELECT id, name, current_version, created_at, updated_at
FROM agents
WHERE id = $1
`

func (q *Queries) GetAgent(ctx context.Context, id uuid.UUID) (Agent, error) {
	row := q.db.QueryRow(ctx, getAgent, id)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CurrentVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAgentVersion = `-- name: GetAgentVersion :one
SELECT agent_id, version, config, config_hash, created_at
FROM agent_versions
WHERE agent_id = $1 AND version = $2
`

type GetAgentVersionParams struct {
	AgentID uuid.UUID
	Version int32
}

func (q *Queries) GetAgentVersion(ctx context.Context, arg GetAgentVersionParams) (AgentVersion, error) {
	row := q.db.QueryRow(ctx, getAgentVersion, arg.AgentID, arg.Version)
	var i AgentVersion
	err := row.Scan(
		&i.AgentID,
		&i.Version,
		&i.Config,
		&i.ConfigHash,
		&i.CreatedAt,
	)
	return i, err
}

const getCurrentAgentVersion = `-- name: GetCurrentAgentVersion :one
SELECT v.agent_id, v.version, v.config, v.config_hash, v.created_at
FROM agent_versions v
JOIN agents a ON a.id = v.agent_id AND a.current_version = v.version
WHERE a.id = $1
`

func (q *Queries) GetCurrentAgentVersion(ctx context.Context, id uuid.UUID) (AgentVersion, error) {
	row := q.db.QueryRow(ctx, getCurrentAgentVersion, id)
	var i AgentVersion
	err := row.Scan(
		&i.AgentID,
		&i.Version,
		&i.Config,
		&i.ConfigHash,
		&i.CreatedAt,
	)
	return i, err
}

const insertAgentVersion = `-- name: InsertAgentVersion :one
INSERT INTO agent_versions (agent_id, version, config, config_hash)
VALUES ($1, $2, $3, $4)
RETURNING agent_id, version, config, config_hash, created_at
`

type InsertAgentVersionParams struct {
	AgentID    uuid.UUID
	Version    int32
	Config     json.RawMessage
	ConfigHash string
}

func (q *Queries) InsertAgentVersion(ctx context.Context, arg InsertAgentVersionParams) (AgentVersion, error) {
	row := q.db.QueryRow(ctx, insertAgentVersion,
		arg.AgentID,
		arg.Version,
		arg.Config,
		arg.ConfigHash,
	)
	var i AgentVersion
	err := row.Scan(
		&i.AgentID,
		&i.Version,
		&i.Config,
		&i.ConfigHash,
		&i.CreatedAt,
	)
	return i, err
}

const listAgents = `-- name: ListAgents :many
SELECT id, name, current_version, created_at, updated_at
FROM agents
ORDER BY created_at DESC
LIMIT 200
`

func (q *Queries) ListAgents(ctx context.Context) ([]Agent, error) {
	rows, err := q.db.Query(ctx, listAgents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Agent
	for rows.Next() {
		var i Agent
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CurrentVersion,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockAgent = `-- name: LockAgent :one
SELECT id, name, current_version, created_at, updated_at
FROM agents
WHERE id = $1
FOR UPDATE
`

func (q *Queries) LockAgent(ctx context.Context, id uuid.UUID) (Agent, error) {
	row := q.db.QueryRow(ctx, lockAgent, id)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CurrentVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const maxAgentVersion = `-- name: MaxAgentVersion :one
SELECT COALESCE(MAX(version), 0)::int AS max_version
FROM agent_versions
WHERE agent_id = $1
`

func (q *Queries) MaxAgentVersion(ctx context.Context, agentID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, maxAgentVersion, agentID)
	var max_version int32
	err := row.Scan(&max_version)
	return max_version, err
}

const setAgentCurrentVersion = `-- name: SetAgentCurrentVersion :exec
UPDATE agents
SET current_version = $2, updated_at = now()
WHERE id = $1
`

type SetAgentCurrentVersionParams struct {
	ID             uuid.UUID
	CurrentVersion pgtype.Int4
}

func (q *Queries) SetAgentCurrentVersion(ctx context.Context, arg SetAgentCurrentVersionParams) error {
	_, err := q.db.Exec(ctx, setAgentCurrentVersion, arg.ID, arg.CurrentVersion)
	return err
}
