// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package store

import (
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Agent struct {
	ID             uuid.UUID
	Name           string
	CurrentVersion pgtype.Int4
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type AgentVersion struct {
	AgentID    uuid.UUID
	Version    int32
	Config     json.RawMessage
	ConfigHash string
	CreatedAt  pgtype.Timestamptz
}
