// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package store

import (
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Agent struct {
	ID             uuid.UUID
	Name           string
	CurrentVersion pgtype.Int4
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type AgentVersion struct {
	AgentID    uuid.UUID
	Version    int32
	Config     json.RawMessage
	ConfigHash string
	CreatedAt  pgtype.Timestamptz
}

type Run struct {
	ID             uuid.UUID
	SessionID      uuid.UUID
	AgentID        uuid.UUID
	AgentVersion   int32
	Config         json.RawMessage
	Input          string
	Status         string
	Attempt        int32
	MaxAttempts    int32
	LeaseOwner     pgtype.Text
	LeaseExpiresAt pgtype.Timestamptz
	Result         []byte
	ErrorCode      pgtype.Text
	ErrorMessage   pgtype.Text
	CreatedAt      pgtype.Timestamptz
	StartedAt      pgtype.Timestamptz
	FinishedAt     pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type Session struct {
	ID        uuid.UUID
	AgentID   uuid.UUID
	Title     string
	CreatedAt pgtype.Timestamptz
}
