// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: runtime.sql

package store

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const claimRun = `-- name: ClaimRun :one
WITH picked AS (
    SELECT id
    FROM runs
    WHERE status = 'queued'
    ORDER BY created_at
    FOR UPDATE SKIP LOCKED
    LIMIT 1
)
UPDATE runs
SET status = 'running',
    attempt = attempt + 1,
    lease_owner = $1,
    lease_expires_at = now() + make_interval(secs => $2::int),
    started_at = COALESCE(started_at, now()),
    updated_at = now()
FROM picked
WHERE runs.id = picked.id
RETURNING runs.id, runs.session_id, runs.attempt, runs.config, runs.input
`

type ClaimRunParams struct {
	LeaseOwner   pgtype.Text
	LeaseSeconds int32
}

type ClaimRunRow struct {
	ID        uuid.UUID
	SessionID uuid.UUID
	Attempt   int32
	Config    json.RawMessage
	Input     string
}

// 领取必须是一条语句。先查再更新时，两个 worker 会领到同一行。
// SKIP LOCKED 让后到的语句跳过已经被锁住的行，而不是排队等它提交。
func (q *Queries) ClaimRun(ctx context.Context, arg ClaimRunParams) (ClaimRunRow, error) {
	row := q.db.QueryRow(ctx, claimRun, arg.LeaseOwner, arg.LeaseSeconds)
	var i ClaimRunRow
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Attempt,
		&i.Config,
		&i.Input,
	)
	return i, err
}

const completeRun = `-- name: CompleteRun :execrows
UPDATE runs
SET status = $1,
    result = $2,
    error_code = $3,
    error_message = $4,
    finished_at = now(),
    lease_owner = NULL,
    lease_expires_at = NULL,
    updated_at = now()
WHERE id = $5
  AND attempt = $6
  AND lease_owner = $7
  AND status = 'running'
`

type CompleteRunParams struct {
	Status       string
	Result       []byte
	ErrorCode    pgtype.Text
	ErrorMessage pgtype.Text
	ID           uuid.UUID
	Attempt      int32
	LeaseOwner   pgtype.Text
}

func (q *Queries) CompleteRun(ctx context.Context, arg CompleteRunParams) (int64, error) {
	result, err := q.db.Exec(ctx, completeRun,
		arg.Status,
		arg.Result,
		arg.ErrorCode,
		arg.ErrorMessage,
		arg.ID,
		arg.Attempt,
		arg.LeaseOwner,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const lockRunForTool = `-- name: LockRunForTool :one
SELECT config
FROM runs
WHERE id = $1
  AND attempt = $2
  AND lease_owner = $3
  AND status = 'running'
FOR SHARE
`

type LockRunForToolParams struct {
	ID         uuid.UUID
	Attempt    int32
	LeaseOwner pgtype.Text
}

// 和完成写在同一条租约条件上，并 FOR SHARE。
// 没有这把共享锁的话，完成请求可以插在「检查通过」和「执行」中间。
func (q *Queries) LockRunForTool(ctx context.Context, arg LockRunForToolParams) (json.RawMessage, error) {
	row := q.db.QueryRow(ctx, lockRunForTool, arg.ID, arg.Attempt, arg.LeaseOwner)
	var config json.RawMessage
	err := row.Scan(&config)
	return config, err
}
