-- +goose Up
REVOKE CREATE ON SCHEMA public FROM PUBLIC;
GRANT USAGE ON SCHEMA public TO cd_app;

ALTER DEFAULT PRIVILEGES FOR ROLE cd_migrate IN SCHEMA public
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO cd_app;

CREATE SCHEMA lg AUTHORIZATION cd_migrate;
GRANT USAGE ON SCHEMA lg TO cd_kernel;

ALTER DEFAULT PRIVILEGES FOR ROLE cd_migrate IN SCHEMA lg
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO cd_kernel;

-- +goose Down
DROP SCHEMA IF EXISTS lg CASCADE;
ALTER DEFAULT PRIVILEGES FOR ROLE cd_migrate IN SCHEMA public
  REVOKE SELECT, INSERT, UPDATE, DELETE ON TABLES FROM cd_app;
GRANT CREATE ON SCHEMA public TO PUBLIC;
